# SPDX-FileCopyrightText: 2023 Melissa LeBlanc-Williams for Adafruit Industries
#
# SPDX-License-Identifier: MIT

contact_links:
  - name: 📟 New Board Request
    url: https://github.com/adafruit/Adafruit_Blinka/discussions/new?category=new-board-requests&labels=New%20Board%20Request
    about: Request Support for a New Board
  - name: 🔗 Adafruit Forum
    url: https://forums.adafruit.com/
    about: Official Adafruit technical support forum. Good for getting help on getting a project working.
  - name: 🔗 Adafruit Discord
    url: https://adafru.it/discord
    about: Unofficial chat with many helpful folks and normally prompt replies.
